version: '3'

services:
  webapplication_mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  webapplication1_mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

